# Changes here will be overwritten by Copier
_commit: v0.0.1
_src_path: gh:ninanor/python-template
author_name: Benjamin Cretois
debug: false
default_branch_name: main
docker: false
email: benjamin.cretois@nina.no
project_name: birdnetfs
project_slug: birdnetfs
repo_name: birdnetfs
repo_org: ninanor
template_type: python
type_annotations: false
